### ISSUE TITLE
Tests & releases

### ISSUE THREAD

**Issue by aeplay** [Longor1996/nanval#4]
Hi @Longor1996 

Thanks for making this. I found it to be the cleanest crate for NaN-boxing I've seen, even if it is a bit buggy - I filed some PRs.

Some tests would be great, I might get around to writing some myself in the future.

Because I need to iterate quite quickly, I published my fork as a crate as well, but if you merge my PRs I would be happy to switch back to yours as a dependency.

**Comment by Longor1996** [comment]
All fixes upstreamed. Released update `v0.2.1` immediately via 0de9021d62ac0ad647f5e0a2f03f451d6a37992f

**Comment by Longor1996** [comment]
Published `v0.2.1` to [crates.io](https://crates.io/crates/nanval).

**Comment by aeplay** [comment]
Thank you very much!
